/**
 * fixtures_mayers_ocr.js — REAL Drive-OCR text for Mayers documents.
 *
 * Harvested 2026-08-20 by runMayersOcrHarvest() into Google Doc
 * 1sbid-4-VnA0o8et5Dr8OGXyn8ZyXg12k0QCQ9-UZ_Qc, which captured
 * DocumentApp.openById(...).getBody().getText() for one PDF per shop hint.
 *
 * WHY THIS FILE EXISTS. The previous mayersShopFromText_ fixtures were written
 * from the regex rather than from an invoice — test_code.js asserted the
 * singular 'BLUE ST' that no Mayers invoice has ever contained. That is how
 * 1112 green tests coexisted with a live money bug for two months
 * (docs/mayers-location-fix-decisions.md, decision 8). Every shop-attribution
 * case is now anchored to text a real invoice actually produced.
 *
 * DO NOT "tidy" these strings. The double-printed header lines, the run-on
 * 'LEIBLE COFFEE NORTH SYDNEY LEGEND STAR INVESTMENTS PTY LTD 5 BLUES ST', the
 * trailing spaces and the blank-line runs are all artefacts of Drive OCR, and
 * they are exactly what the parser has to survive. pdftotext output is NOT a
 * valid substitute — measured 2026-08-14, the same invoice fails all three
 * production regexes under pdftotext while parsing fine under Drive OCR.
 *
 * Contents (matching the live Suppliers rows they produced):
 *   3446281  $570.15  wk 2026-07-27  North  — the misfiled row this repair fixes
 *   3463868 $1140.30  wk 2026-08-10  Pitt   — regression guard
 *   3434688  $703.80  wk 2026-06-29  York   — regression guard
 *   LEI04D statement  — parses to null, permanently; the OCR quota-leak case
 */

'use strict';

/* Invoice 3446281 — 31-JUL-26, $570.15, account LEI07D (North Sydney).
 * Deliver-To reads '5 BLUES ST'. The plural is the whole defect: /\bBLUE\s*ST/i
 * matches 'BLUE' inside 'BLUES', then requires 'ST' where an 'S' stands. */
const MAYERS_OCR_3446281_NORTH = [
  'F.Mayer Imports Pty Ltd TAX INVOICE   ',
  'F.Mayer Imports Pty Ltd TAX INVOICE Correspondence To:   ',
  'Correspondence To:   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'Email: remittance@mayers.com.au   ',
  'Email: remittance@mayers.com.au   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'Reason: Del Date: 01-AUG-26   ',
  'Reason: Del Date: 01-AUG-26   ',
  'Invoice No: Invoice No:   ',
  '3446281   ',
  '3446281  ',
  'Invoice Date: Invoice Date:   ',
  '31-JUL-26 31-JUL-26   ',
  'Priority: Priority:   ',
  '66  ',
  '  ',
  '  ',
  '  ',
  'Bill To :   ',
  '  ',
  '  ',
  'LEIBLE COFFEE NORTH SYDNEY LEGEND STAR INVESTMENTS PTY LTD 5 BLUES ST   ',
  'NORTH SYDNEY   ',
  'NSW 2060   ',
  'Phone: 0468730171 JT  ',
  'Deliver To:  ',
  '  ',
  '  ',
  'LEIBLE COFFEE NORTH SYDNEY 5 BLUES ST   ',
  'NORTH SYDNEY   ',
  'NSW 2060   ',
  'Mobile : 0433801354 JA   ',
  '  ',
  'Account:   ',
  '  ',
  'LEI07D   ',
  '  ',
  'Delivery   ',
  'Instructions :  ',
  'OPENING HOURS 7:30AM10  ',
  '  ',
  'Order Reference:   ',
  '  ',
  'JACK  ',
  '  ',
  'Warehouse:   ',
  '  ',
  'SYD  ',
  '  ',
  'Entered By:   ',
  '  ',
  'franki  ',
  '  ',
  'Rep:   ',
  '  ',
  'FRANK  ',
  '  ',
  'FOR ONLINE ORDERING.   ',
  'Please go to www.mayers.com.au, Click on the LOGIN LOGO/BUTTO and follow the prompts or please email customer service on enquirescs@mayers.com.a to gain access.  ',
  '  ',
  'Ordere   ',
  'Picked   ',
  'Item Code   ',
  'Item Description   ',
  '  ',
  '  ',
  'Shipped Qty Unit Price   ',
  '  ',
  'Disc   ',
  'CD   ',
  '  ',
  'Net Price Line Total  ',
  '1   ',
  '1CTN   ',
  '823NV595   ',
  'MILK CALLETS 33.6% 2X10KG   ',
  '  ',
  '  ',
  '1.00 CTN   ',
  '570.15   ',
  '  ',
  '0.00   ',
  '570.15   ',
  '570.15  ',
  '  ',
  '  ',
  'Please Note: Arla Mayer and F.Mayer invoices must be paid into separate accounts.   ',
  'EFT Details for this invoice are below  ',
  '  ',
  "Claims & Returns : The customer will inspect and check all products received and within 2 days of receipt notify the company in writing of anyshortage in quantity, defect, incorrect specification, damage or products not in accordance with the customer's order.   ",
  'Please keep all perishable goods constantly under refrigeration: Chiller < 5C, Frozen < -15C  ',
  'PAYMENT DETAILS  ',
  'Ex Tax:   ',
  '570.15  ',
  '  ',
  'BSB: 032-007   ',
  'Account: 610828   ',
  'Pay Ref: 3446281  ',
  'GST   ',
  '0.00  ',
  '  ',
  '  ',
  'Total:   ',
  '570.15  ',
  '  ',
  '  ',
  'All goods remain the property of Arla Foods Mayer Australia Pty Ltd until paid in full. In default of such prompt payment, you undertake to pay late payment fee 2.5% per month on any amount outstanding and to indemnify us and pay all costs and expenses on a solicitor/client bases if legal action is necessary, and or Credit Collection fees, which we may incur in recovering from you any overdue account.  ',
  '* Indicates Taxable item. # indicates CDS applicable items. print date&time: 31/07/2026 6:32:03 AM Page 1 of 1 * Indicates Taxable item. # indicates CDS applicable items. print date&time: 31/07/2026 6:32:03 AM Page 1 of 1   ',
].join('\n');

/* Invoice 3463868 — 12-AUG-26, $1,140.30, account LEI06D (Pitt St).
 * hasBLUES_ST is false here, so the widened rule cannot steal it. */
const MAYERS_OCR_3463868_PITT = [
  'F.Mayer Imports Pty Ltd TAX INVOICE   ',
  'F.Mayer Imports Pty Ltd TAX INVOICE Correspondence To:   ',
  'Correspondence To:   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'Email: remittance@mayers.com.au   ',
  'Email: remittance@mayers.com.au   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'Reason: Del Date: 13-AUG-26   ',
  'Reason: Del Date: 13-AUG-26   ',
  'Invoice No: Invoice No:   ',
  '3463868   ',
  '3463868  ',
  'Invoice Date: Invoice Date:   ',
  '12-AUG-26 12-AUG-26   ',
  'Priority: Priority:   ',
  '55  ',
  '  ',
  '  ',
  '  ',
  'Bill To :   ',
  '  ',
  '  ',
  'LEIBLE COFFEE PITT   ',
  'MZCOFFEE PTY LTD   ',
  '130 PITT ST   ',
  '(ON THE MIDDLE OF LEES CT) LG1 SYDNEY   ',
  'NSW 2000   ',
  'Phone: 0468730171 JT  ',
  'Deliver To:  ',
  '  ',
  '  ',
  'LEIBLE COFFEE PITT   ',
  '130 PITT ST   ',
  '(ON THE MIDDLE OF LEES CT) LG1 SYDNEY   ',
  'NSW 2000   ',
  'Mobile : 0433801354 JA   ',
  '  ',
  'Account:   ',
  '  ',
  'LEI06D   ',
  '  ',
  'Delivery   ',
  'Instructions :  ',
  'OPENING HOURS 7:30AM1  ',
  '  ',
  'Order Reference:   ',
  '  ',
  'JUSTIN PITT ST DELIV  ',
  '  ',
  'Warehouse:   ',
  '  ',
  'SYD  ',
  '  ',
  'Entered By:   ',
  '  ',
  'franki  ',
  '  ',
  'Rep:   ',
  '  ',
  'FRANK  ',
  '  ',
  'FOR ONLINE ORDERING.   ',
  'Please go to www.mayers.com.au, Click on the LOGIN LOGO/BUTTO and follow the prompts or please email customer service on enquirescs@mayers.com.a to gain access.  ',
  '  ',
  'Ordere   ',
  'Picked   ',
  'Item Code   ',
  'Item Description   ',
  '  ',
  '  ',
  'Shipped Qty Unit Price   ',
  '  ',
  'Disc   ',
  'CD   ',
  '  ',
  'Net Price Line Total  ',
  '2   ',
  '2CTN   ',
  '823NV595   ',
  'MILK CALLETS 33.6% 2X10KG   ',
  '  ',
  '  ',
  '2.00 CTN   ',
  '570.15   ',
  '  ',
  '0.00   ',
  '570.15   ',
  '1,140.30  ',
  '  ',
  '  ',
  'Please Note: Arla Mayer and F.Mayer invoices must be paid into separate accounts.   ',
  'EFT Details for this invoice are below  ',
  '  ',
  "Claims & Returns : The customer will inspect and check all products received and within 2 days of receipt notify the company in writing of anyshortage in quantity, defect, incorrect specification, damage or products not in accordance with the customer's order.   ",
  'Please keep all perishable goods constantly under refrigeration: Chiller < 5C, Frozen < -15C  ',
  'PAYMENT DETAILS  ',
  'Ex Tax:   ',
  '1,140.30  ',
  '  ',
  'BSB: 032-007   ',
  'Account: 610828   ',
  'Pay Ref: 3463868  ',
  'GST   ',
  '0.00  ',
  '  ',
  '  ',
  'Total:   ',
  '1,140.30  ',
  '  ',
  '  ',
  'All goods remain the property of Arla Foods Mayer Australia Pty Ltd until paid in full. In default of such prompt payment, you undertake to pay late payment fee 2.5% per month on any amount outstanding and to indemnify us and pay all costs and expenses on a solicitor/client bases if legal action is necessary, and or Credit Collection fees, which we may incur in recovering from you any overdue account.  ',
  '* Indicates Taxable item. # indicates CDS applicable items. print date&time: 12/08/2026 6:19:00 AM Page 1 of 1 * Indicates Taxable item. # indicates CDS applicable items. print date&time: 12/08/2026 6:19:00 AM Page 1 of 1   ',
].join('\n');

/* Invoice 3434688 — 30-JUN-26, $703.80, account LEI05D (York St).
 * Same account code as 3429816, the blank-location row Phase 2 repairs to York. */
const MAYERS_OCR_3434688_YORK = [
  'F.Mayer Imports Pty Ltd TAX INVOICE   ',
  'F.Mayer Imports Pty Ltd TAX INVOICE Correspondence To:   ',
  'Correspondence To:   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'PO Box 196, Matraville, NSW. 2036   ',
  'Email: remittance@mayers.com.au   ',
  'Email: remittance@mayers.com.au   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'B1 2-8 Mcpherson Street Ph: 02 9669 2211   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'Banksmeadow Fax: 02 9669 1051   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'A.B.N: 51000697889 NSW 2019   ',
  'Reason: Del Date: 01-JUL-26   ',
  'Reason: Del Date: 01-JUL-26   ',
  'Invoice No: Invoice No:   ',
  '3434688   ',
  '3434688  ',
  'Invoice Date: Invoice Date:   ',
  '30-JUN-26 30-JUN-26   ',
  'Priority: Priority:   ',
  '55  ',
  '  ',
  '  ',
  '  ',
  'Bill To :   ',
  '  ',
  '  ',
  'LEIBLE COFFEE   ',
  'KAFFAPRO PTY LTD   ',
  '89 YORK ST   ',
  'LEIBLE COFFEE, GROUND LEVEL SYDNEY   ',
  'NSW 2000   ',
  'Phone: 0468730171 JT  ',
  'Deliver To:  ',
  '  ',
  '  ',
  'LEIBLE COFFEE   ',
  '89 YORK ST   ',
  'LEIBLE COFFEE, GROUND LEVEL SYDNEY   ',
  'NSW 2000   ',
  'Mobile : 0433801354 JA   ',
  '  ',
  'Account:   ',
  '  ',
  'LEI05D   ',
  '  ',
  'Delivery   ',
  'Instructions :  ',
  'OPENING HOURS 7:30AM1  ',
  '  ',
  'Order Reference:   ',
  '  ',
  'EMAIL  ',
  '  ',
  'Warehouse:   ',
  '  ',
  'SYD  ',
  '  ',
  'Entered By:   ',
  '  ',
  'franki  ',
  '  ',
  'Rep:   ',
  '  ',
  'FRANK  ',
  '  ',
  'FOR ONLINE ORDERING.   ',
  'Please go to www.mayers.com.au, Click on the LOGIN LOGO/BUTTO and follow the prompts or please email customer service on enquirescs@mayers.com.a to gain access.  ',
  '  ',
  'Ordere   ',
  'Picked   ',
  'Item Code   ',
  'Item Description   ',
  '  ',
  '  ',
  'Shipped Qty Unit Price   ',
  '  ',
  'Disc   ',
  'CD   ',
  '  ',
  'Net Price Line Total  ',
  '1   ',
  '1CTN   ',
  '8232BU76   ',
  'CAL MILK CALLET 33.6% 8X2.5KG   ',
  '  ',
  '  ',
  '1.00 CTN   ',
  '890.89   ',
  '21.00% 0.00   ',
  '  ',
  '703.80   ',
  '703.80  ',
  '  ',
  '  ',
  'Please Note: Arla Mayer and F.Mayer invoices must be paid into separate accounts.   ',
  'EFT Details for this invoice are below  ',
  '  ',
  "Claims & Returns : The customer will inspect and check all products received and within 2 days of receipt notify the company in writing of anyshortage in quantity, defect, incorrect specification, damage or products not in accordance with the customer's order.   ",
  'Please keep all perishable goods constantly under refrigeration: Chiller < 5C, Frozen < -15C  ',
  'PAYMENT DETAILS  ',
  'Ex Tax:   ',
  '703.80  ',
  '  ',
  'BSB: 032-007   ',
  'Account: 610828   ',
  'Pay Ref: 3434688  ',
  'GST   ',
  '0.00  ',
  '  ',
  '  ',
  'Total:   ',
  '703.80  ',
  '  ',
  '  ',
  'All goods remain the property of Arla Foods Mayer Australia Pty Ltd until paid in full. In default of such prompt payment, you undertake to pay late payment fee 2.5% per month on any amount outstanding and to indemnify us and pay all costs and expenses on a solicitor/client bases if legal action is necessary, and or Credit Collection fees, which we may incur in recovering from you any overdue account.  ',
  '* Indicates Taxable item. # indicates CDS applicable items. print date&time: 30/06/2026 6:05:12 AM Page 1 of 1 * Indicates Taxable item. # indicates CDS applicable items. print date&time: 30/06/2026 6:05:12 AM Page 1 of 1   ',
].join('\n');

/* Monthly account statement LEI04D_31 JUL 26.pdf — NOT an invoice.
 * No 'Invoice No', no 'Deliver To', and its only Total is a balance with no
 * cents-anchored value adjacent, so parseMayersInvoice_ returns null. This is
 * the document that was re-OCR'd every day until the unparseable memo (8ae39d8)
 * shipped, and the case that proves the memo has something real to remember. */
const MAYERS_OCR_STATEMENT_LEI04D = [
  '  ',
  'A.B.N: 51000697889   ',
  'Statement For:   ',
  'LEIBLE COFFEE ROASTERY   ',
  'F Mayer Imports Pty Ltd   ',
  'Correspondence To:   ',
  'Email: remittance@mayers.com.au Statement Date: 31 - JUL - 26 P.O. Box 196   ',
  'Matraville, NSW, 2036.   ',
  'Australia   ',
  'Phone: 02 9669 2211   ',
  'REMITTANCE   ',
  'LEIBLE COFFEE ROASTERS PTY LTD 4 BURLINGTON ST   ',
  'GROUND LEVEL   ',
  'CROWS NEST   ',
  'NSW 2065   ',
  'Ph: 0433 801 354 J Fax: 0433 801 354   ',
  'ADVICE STATEMENT Account:LEI04D Account:LEI04D   ',
  '  ',
  'Date   ',
  'Doc #   ',
  '  ',
  'Reference   ',
  '  ',
  '  ',
  'Type   ',
  'Amount   ',
  '  ',
  'Balance   ',
  'Reference   ',
  '  ',
  'Amount   ',
  'Balance  ',
  '08-APR-2026 08-APR-2026 08-APR-2026   ',
  '3403441   ',
  '3403441   ',
  '3403441   ',
  '  ',
  'INTERNET REC   ',
  'MJ   ',
  'ECEC   ',
  '  ',
  '  ',
  'CR   ',
  'IN   ',
  'CR   ',
  '-703.75   ',
  '703.75   ',
  '-703.75   ',
  '  ',
  '-703.75   ',
  '0.00   ',
  '-703.75   ',
  '3403441   ',
  '3403441   ',
  '3403441   ',
  '  ',
  '-703.75   ',
  '703.75   ',
  '-703.75   ',
  '-703.75   ',
  '0.00   ',
  '-703.75  ',
  '  ',
  '90+ days   ',
  '  ',
  '60 days   ',
  '  ',
  '30 days   ',
  'Current   ',
  '  ',
  '  ',
  'Total Balance Due   ',
  '  ',
  '  ',
  'Amount Paid  ',
  '  ',
  '  ',
  '-$703.75   ',
  '  ',
  '$0.00   ',
  '  ',
  '$0.00   ',
  '$0.00   ',
  '  ',
  '  ',
  '-$703.75   ',
  '  ',
  '  ',
  '-$703.75  ',
  '  ',
  '  ',
  'BSB: 032-007Account no.: 610828  ',
  '  ',
  'Payment details for F Mayer Imports Pty Ltd  ',
  '  ',
  'This account is   ',
  '  ',
  '> 1 month overdue   ',
  '  ',
  'PAYMENT DETAILS  ',
  '  ',
  '  ',
  'All Accounts: Pay according to payment terms  ',
  '  ',
  '  ',
  '  ',
  'Interest will be added to any invoice not paid within agreement terms.CLAIMS: Please keep all perishable goods constantly   ',
  '  ',
  'BSB: 032-007   ',
  'Account: 610828   ',
  'Pay Ref: LEI04D   ',
  'Company Name:   ',
  'F Mayer Imports Pty Ltd  ',
  '  ',
  'All goods remain the property of F Mayer Imports Pty Ltd until paid in full.   ',
  'In default of such prompt payment, you undertake to pay late payment fee 2.5% per month on any amount outstanding and to indemnify us and pay all costs and expenses on a solicitor/client bases if legal action is necessary, and /or Credit Collection fees, which we may incur in recovering from you any overdue account.   ',
  'Returns will only be accepted if notified within 1 day of delivery.  ',
  'Page 1 of 1 ',
].join('\n');

module.exports = {
  MAYERS_OCR_3446281_NORTH,
  MAYERS_OCR_3463868_PITT,
  MAYERS_OCR_3434688_YORK,
  MAYERS_OCR_STATEMENT_LEI04D,
};
